# Generated by Django 5.1 on 2024-08-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUrlsForScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(choices=[('KN', 'kitabnow.com'), ('BB', 'bookberry.com'), ('RC', 'readings.com.pk'), ('VB', 'vanguardbooks.com')], max_length=5)),
            ],
        ),
    ]
