# Generated by Django 5.1 on 2024-09-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_weburlsforscrape_category_name_weburlsforscrape_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrecord',
            name='category_id',
            field=models.CharField(default='RC', max_length=5),
        ),
        migrations.AlterField(
            model_name='weburlsforscrape',
            name='url',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='weburlsforscrape',
            name='web_name',
            field=models.CharField(choices=[('RC', 'readings.com.pk'), ('GB', 'globalbooks.com'), ('LB', 'libertybooks.com'), ('KN', 'kitabnow.com'), ('BB', 'bookberry.com'), ('VB', 'vanguardbooks.com')], max_length=5),
        ),
    ]
