# Generated by Django 5.1 on 2024-09-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_booksrecord_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weburlsforscrape',
            name='web_name',
            field=models.CharField(choices=[('KN', 'kitabnow.com'), ('LB', 'libertybooks.com'), ('BB', 'bookberry.com'), ('VB', 'vanguardbooks.com'), ('GB', 'globalbooks.com'), ('RC', 'readings.com.pk')], max_length=5),
        ),
    ]
